import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 class="text-center font-bold text-2xl">I'am Marvin Ebuenga</h1>
    </div>
  );
}
